sudo: required
dist: trusty
language: ruby
rvm:
- "2.4"
python:
- "2.7"
install:
- rake setup:develop
script:
- bash bin/versionCheck.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
- rake test
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
