sudo: false
language: python
python: 2.7
install:
  - pip install tox-travis
  - pip install codacy-coverage
script:
- mkdir reports # workaround for travis error when writing to this dir
- bash bin/versionCheck.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
- tox
- python-codacy-coverage -r reports/coverage.xml
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
